-- Generated by scripts/build-mobile-image-migration.mjs --generate. Review the explicit SQL before application.

-- Source schema SHA-256: 08a627a65bb88537c7d935d4b312fac3de51849639d1872a9bdc8be1c10cc2a8. Foreign keys remain enabled.

PRAGMA defer_foreign_keys = ON;

CREATE TABLE media_0026_backup AS SELECT * FROM media;

CREATE TABLE media_object_promotions_0026_backup AS SELECT * FROM media_object_promotions;

DROP TRIGGER events_media_capacity_guard_insert;

DROP TRIGGER events_media_capacity_guard_update;

DROP TRIGGER export_jobs_retry_source_fence;

DROP TRIGGER legacy_media_scan_quarantine_permanent;

DROP TRIGGER legacy_media_scan_state_permanent;

DROP TRIGGER media_album_pick_generation_delete;

DROP TRIGGER media_album_pick_generation_update;

DROP TRIGGER media_album_pick_pair_guard;

DROP TRIGGER media_album_pick_version_on_legacy_pick;

DROP TRIGGER media_album_pick_version_on_legacy_unpick;

DROP TRIGGER media_delivery_sequence_insert;

DROP TRIGGER media_delivery_sequence_stored;

DROP TRIGGER media_object_promotion_inventory_insert;

DROP TRIGGER media_object_promotion_inventory_update;

DROP TRIGGER media_object_promotion_reservation_capability_guard;

DROP TRIGGER media_object_promotion_verified_delete_guard;

DROP TRIGGER media_object_promotion_verified_proof_immutable;

DROP TRIGGER media_object_write_tombstone_guard_insert;

DROP TRIGGER media_object_write_tombstone_guard_update;

DROP TRIGGER media_object_write_tombstone_immutable;

DROP TRIGGER media_object_write_tombstone_inventory_insert;

DROP TRIGGER media_object_write_tombstone_inventory_update;

DROP TRIGGER media_object_write_tombstone_permanent;

DROP TRIGGER media_recoverable_owner_tombstone_insert;

DROP TRIGGER media_recoverable_owner_tombstone_suppress;

DROP TRIGGER media_stamp_stored_at_compat;

DROP TRIGGER media_stored_legacy_guard_insert;

DROP TRIGGER media_stored_legacy_guard_update;

DROP TRIGGER media_trash_pair_insert;

DROP TRIGGER media_trash_pair_update;

DROP TABLE media_object_promotions;

DROP TABLE media;

CREATE TABLE "media" (
  id TEXT PRIMARY KEY,
  event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  uploader_session_id TEXT NOT NULL REFERENCES event_sessions(id) ON DELETE RESTRICT,
  object_key TEXT NOT NULL UNIQUE,
  original_filename TEXT NOT NULL,
  mime_type TEXT NOT NULL CHECK (mime_type IN (
    'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif',
    'image/heic-sequence', 'image/heif-sequence', 'image/dng', 'image/avif',
    'image/avif-sequence', 'image/gif', 'image/tiff', 'image/bmp', 'image/jp2', 'image/jxl'
  )),
  declared_byte_size INTEGER NOT NULL CHECK (declared_byte_size > 0),
  byte_size INTEGER,
  width INTEGER,
  height INTEGER,
  guest_name TEXT NOT NULL CHECK (length(trim(guest_name)) BETWEEN 1 AND 80),
  caption TEXT CHECK (caption IS NULL OR length(caption) <= 300),
  upload_state TEXT NOT NULL CHECK (upload_state IN ('reserved', 'stored', 'failed', 'deleted')),
  publication_status TEXT NOT NULL CHECK (publication_status IN ('unpublished', 'published', 'hidden')),
  idempotency_key TEXT NOT NULL,
  reservation_expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  published_at TEXT,
  preview_object_key TEXT,
  deleted_at TEXT, stored_at TEXT, object_bucket_generation TEXT NOT NULL DEFAULT 'legacy'
  CHECK (object_bucket_generation IN ('legacy', 'canonical')), captured_at TEXT, timeline_at TEXT NOT NULL
  DEFAULT '1970-01-01T00:00:00.000Z', favorited_at TEXT, trashed_at TEXT, restore_until TEXT, album_pick_version INTEGER
  CHECK (album_pick_version IS NULL OR album_pick_version = 1), delivery_sequence INTEGER
  CHECK (delivery_sequence IS NULL OR delivery_sequence > 0),
  UNIQUE (event_id, uploader_session_id, idempotency_key)
);

INSERT INTO media (id, event_id, uploader_session_id, object_key, original_filename, mime_type, declared_byte_size, byte_size, width, height, guest_name, caption, upload_state, publication_status, idempotency_key, reservation_expires_at, created_at, published_at, preview_object_key, deleted_at, stored_at, object_bucket_generation, captured_at, timeline_at, favorited_at, trashed_at, restore_until, album_pick_version, delivery_sequence) SELECT id, event_id, uploader_session_id, object_key, original_filename, mime_type, declared_byte_size, byte_size, width, height, guest_name, caption, upload_state, publication_status, idempotency_key, reservation_expires_at, created_at, published_at, preview_object_key, deleted_at, stored_at, object_bucket_generation, captured_at, timeline_at, favorited_at, trashed_at, restore_until, album_pick_version, delivery_sequence FROM media_0026_backup;

DROP TABLE media_0026_backup;

CREATE TABLE media_object_promotions (
  media_id TEXT PRIMARY KEY REFERENCES media(id) ON DELETE RESTRICT,
  event_id TEXT NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
  source_bucket_generation TEXT NOT NULL DEFAULT 'legacy'
    CHECK (source_bucket_generation = 'legacy'),
  source_object_key TEXT NOT NULL,
  final_bucket_generation TEXT NOT NULL DEFAULT 'canonical'
    CHECK (final_bucket_generation = 'canonical'),
  final_object_key TEXT NOT NULL UNIQUE,
  source_etag TEXT,
  source_mime_type TEXT,
  source_byte_size INTEGER CHECK (source_byte_size IS NULL OR source_byte_size > 0),
  source_sha256 TEXT CHECK (source_sha256 IS NULL OR length(source_sha256) = 64),
  source_width INTEGER CHECK (source_width IS NULL OR source_width > 0),
  source_height INTEGER CHECK (source_height IS NULL OR source_height > 0),
  final_etag TEXT,
  target_verified_at TEXT,
  source_writable_until TEXT NOT NULL,
  state TEXT NOT NULL
    CHECK (state IN ('pending', 'copying', 'target_verified', 'cleanup_pending')),
  final_pointer_committed INTEGER NOT NULL DEFAULT 0
    CHECK (final_pointer_committed IN (0, 1)),
  claim_token TEXT,
  lease_expires_at TEXT,
  source_absent_since TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (source_absent_since IS NULL OR state = 'cleanup_pending'),
  CHECK (
    (state = 'pending'
      AND final_pointer_committed = 0
      AND claim_token IS NULL AND lease_expires_at IS NULL
      AND source_absent_since IS NULL
      AND source_etag IS NULL AND source_mime_type IS NULL
      AND source_byte_size IS NULL AND source_sha256 IS NULL
      AND source_width IS NULL AND source_height IS NULL
      AND final_etag IS NULL AND target_verified_at IS NULL)
    OR (state = 'copying'
      AND final_pointer_committed = 0
      AND claim_token IS NOT NULL AND lease_expires_at IS NOT NULL
      AND source_absent_since IS NULL
      AND final_etag IS NULL AND target_verified_at IS NULL
      AND (
        (source_etag IS NULL AND source_mime_type IS NULL
          AND source_byte_size IS NULL AND source_sha256 IS NULL
          AND source_width IS NULL AND source_height IS NULL)
        OR (source_etag IS NOT NULL AND source_mime_type IS NOT NULL
          AND source_byte_size IS NOT NULL AND source_sha256 IS NOT NULL
          AND source_width IS NOT NULL AND source_height IS NOT NULL)
      ))
    OR (state = 'target_verified'
      AND final_pointer_committed = 0
      AND claim_token IS NOT NULL AND lease_expires_at IS NULL
      AND source_absent_since IS NULL
      AND source_etag IS NOT NULL AND source_mime_type IS NOT NULL
      AND source_byte_size IS NOT NULL AND source_sha256 IS NOT NULL
      AND source_width IS NOT NULL AND source_height IS NOT NULL
      AND final_etag IS NOT NULL AND target_verified_at IS NOT NULL)
    OR (state = 'cleanup_pending'
      AND claim_token IS NOT NULL AND lease_expires_at IS NULL
      AND (
        (final_pointer_committed = 1
          AND source_etag IS NOT NULL AND source_mime_type IS NOT NULL
          AND source_byte_size IS NOT NULL AND source_sha256 IS NOT NULL
          AND source_width IS NOT NULL AND source_height IS NOT NULL
          AND final_etag IS NOT NULL AND target_verified_at IS NOT NULL)
        OR (final_pointer_committed = 0
          AND (
            (source_etag IS NULL AND source_mime_type IS NULL
              AND source_byte_size IS NULL AND source_sha256 IS NULL
              AND source_width IS NULL AND source_height IS NULL
              AND final_etag IS NULL AND target_verified_at IS NULL)
            OR (source_etag IS NOT NULL AND source_mime_type IS NOT NULL
              AND source_byte_size IS NOT NULL AND source_sha256 IS NOT NULL
              AND source_width IS NOT NULL AND source_height IS NOT NULL
              AND final_etag IS NOT NULL AND target_verified_at IS NOT NULL)
          ))
      ))
  )
);

INSERT INTO media_object_promotions (media_id, event_id, source_bucket_generation, source_object_key, final_bucket_generation, final_object_key, source_etag, source_mime_type, source_byte_size, source_sha256, source_width, source_height, final_etag, target_verified_at, source_writable_until, state, final_pointer_committed, claim_token, lease_expires_at, source_absent_since, created_at, updated_at) SELECT media_id, event_id, source_bucket_generation, source_object_key, final_bucket_generation, final_object_key, source_etag, source_mime_type, source_byte_size, source_sha256, source_width, source_height, final_etag, target_verified_at, source_writable_until, state, final_pointer_committed, claim_token, lease_expires_at, source_absent_since, created_at, updated_at FROM media_object_promotions_0026_backup;

DROP TABLE media_object_promotions_0026_backup;

CREATE UNIQUE INDEX media_event_delivery_sequence
ON media(event_id, delivery_sequence) WHERE delivery_sequence IS NOT NULL;

CREATE INDEX media_event_state ON media(event_id, upload_state, publication_status, created_at);

CREATE INDEX media_guest_gallery_page
ON media(event_id, published_at, created_at, id)
WHERE upload_state = 'stored' AND publication_status = 'published'
  AND deleted_at IS NULL AND trashed_at IS NULL;

CREATE INDEX media_manager_page_all
ON media(event_id, upload_state, created_at DESC, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX media_manager_page_status
ON media(event_id, upload_state, publication_status, created_at DESC, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX media_manager_stored_page_all
ON media(event_id, upload_state, stored_at DESC, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX media_manager_stored_page_status
ON media(event_id, upload_state, publication_status, stored_at DESC, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX media_object_promotions_event_state
ON media_object_promotions(event_id, state, updated_at);

CREATE INDEX media_object_promotions_schedule
ON media_object_promotions(state, updated_at, media_id);

CREATE INDEX media_private_gallery_favorites
ON media(event_id, timeline_at, id)
WHERE upload_state = 'stored'
  AND deleted_at IS NULL
  AND favorited_at IS NOT NULL;

CREATE INDEX media_private_gallery_timeline
ON media(event_id, timeline_at, id)
WHERE upload_state = 'stored' AND deleted_at IS NULL;

CREATE INDEX media_recently_deleted_page
ON media(event_id, trashed_at DESC, id DESC)
WHERE trashed_at IS NOT NULL;

CREATE INDEX media_recovery_expiry
ON media(restore_until, id)
WHERE trashed_at IS NOT NULL;

CREATE INDEX media_reservations ON media(upload_state, reservation_expires_at);

CREATE INDEX media_uploader ON media(uploader_session_id, created_at);

CREATE TRIGGER events_media_capacity_guard_insert
BEFORE INSERT ON events
WHEN NEW.reserved_media_count + NEW.stored_media_count + NEW.recoverable_media_count > 10000
  OR NEW.reserved_bytes + NEW.stored_bytes + NEW.recoverable_bytes > 107374182400
BEGIN
  SELECT RAISE(ABORT, 'event media capacity exceeded');
END;

CREATE TRIGGER events_media_capacity_guard_update
BEFORE UPDATE OF reserved_media_count, stored_media_count, recoverable_media_count,
  reserved_bytes, stored_bytes, recoverable_bytes ON events
WHEN NEW.reserved_media_count + NEW.stored_media_count + NEW.recoverable_media_count > 10000
  OR NEW.reserved_bytes + NEW.stored_bytes + NEW.recoverable_bytes > 107374182400
BEGIN
  SELECT RAISE(ABORT, 'event media capacity exceeded');
END;

CREATE TRIGGER export_jobs_retry_source_fence
BEFORE UPDATE OF state ON export_jobs
WHEN NEW.state = 'queued'
  AND OLD.state IN ('failed', 'expired')
  AND (
    (NEW.kind = 'selection' AND NEW.media_count <= 0)
    OR (NEW.kind = 'complete' AND NEW.guestbook_entry_count IS NULL)
    OR NOT (
      (SELECT count(*) FROM export_media_entries AS e
        WHERE e.export_job_id = NEW.id) = NEW.media_count
      AND COALESCE((SELECT sum(COALESCE(e.byte_size, e.declared_byte_size))
        FROM export_media_entries AS e
        WHERE e.export_job_id = NEW.id), 0) = NEW.total_bytes
      AND NOT EXISTS (
        SELECT 1 FROM export_media_entries AS e
        WHERE e.export_job_id = NEW.id
          AND NOT EXISTS (
            SELECT 1 FROM media_object_write_tombstones AS t
            WHERE t.bucket_generation = e.object_bucket_generation
              AND t.object_key = e.object_key
              AND t.suppression_started_at IS NULL
          )
      )
      AND NOT EXISTS (
        SELECT 1 FROM export_media_entries AS e
        WHERE e.export_job_id = NEW.id
          AND NOT EXISTS (
            SELECT 1 FROM media AS m
            WHERE m.id = e.media_id
              AND m.event_id = NEW.event_id
              AND m.upload_state = 'stored'
              AND m.object_bucket_generation = e.object_bucket_generation
              AND m.object_key = e.object_key
              AND (
                (m.trashed_at IS NULL AND m.deleted_at IS NULL)
                OR (m.trashed_at IS NOT NULL AND m.deleted_at = m.trashed_at)
              )
          )
      )
    )
  )
BEGIN
  SELECT RAISE(ABORT, 'export source hold cannot be reacquired');
END;

CREATE TRIGGER legacy_media_scan_quarantine_permanent
BEFORE DELETE ON legacy_media_scan_quarantine BEGIN
  SELECT RAISE(ABORT, 'legacy media scan quarantine is permanent');
END;

CREATE TRIGGER legacy_media_scan_state_permanent
BEFORE DELETE ON legacy_media_scan_state BEGIN
  SELECT RAISE(ABORT, 'legacy media scan state is permanent');
END;

CREATE TRIGGER media_album_pick_generation_delete
AFTER DELETE ON media
WHEN OLD.favorited_at IS NOT NULL
  AND OLD.upload_state = 'stored'
  AND OLD.deleted_at IS NULL
BEGIN
  UPDATE events
  SET album_pick_generation = album_pick_generation + 1
  WHERE id = OLD.event_id;
END;

CREATE TRIGGER media_album_pick_generation_update
AFTER UPDATE ON media
WHEN (
    OLD.favorited_at IS NOT NULL
    AND OLD.upload_state = 'stored'
    AND OLD.deleted_at IS NULL
  ) <> (
    NEW.favorited_at IS NOT NULL
    AND NEW.upload_state = 'stored'
    AND NEW.deleted_at IS NULL
  )
BEGIN
  UPDATE events
  SET album_pick_generation = album_pick_generation + 1
  WHERE id = NEW.event_id;
END;

CREATE TRIGGER media_album_pick_pair_guard
BEFORE UPDATE OF favorited_at, album_pick_version ON media
WHEN ((NEW.favorited_at IS NOT NULL AND NEW.album_pick_version IS NULL)
   OR (NEW.favorited_at IS NULL AND NEW.album_pick_version IS NOT NULL))
  -- Predecessor pick: stamps arrive one statement later, from the AFTER trigger.
  AND NOT (OLD.favorited_at IS NULL AND NEW.favorited_at IS NOT NULL
           AND NEW.album_pick_version IS NULL AND OLD.album_pick_version IS NULL)
  -- Predecessor unpick: the stale version is cleared one statement later.
  AND NOT (OLD.favorited_at IS NOT NULL AND NEW.favorited_at IS NULL
           AND NEW.album_pick_version IS NOT NULL
           AND NEW.album_pick_version IS OLD.album_pick_version)
BEGIN
  SELECT RAISE(ABORT, 'media.album_pick_version disagrees with media.favorited_at');
END;

CREATE TRIGGER media_album_pick_version_on_legacy_pick
AFTER UPDATE OF favorited_at ON media
WHEN OLD.favorited_at IS NULL
  AND NEW.favorited_at IS NOT NULL
  AND OLD.album_pick_version IS NULL
  AND NEW.album_pick_version IS NULL
BEGIN
  UPDATE media
  SET album_pick_version = 1
  WHERE id = NEW.id
    AND favorited_at IS NEW.favorited_at
    AND album_pick_version IS NULL;
END;

CREATE TRIGGER media_album_pick_version_on_legacy_unpick
AFTER UPDATE OF favorited_at ON media
WHEN OLD.favorited_at IS NOT NULL
  AND NEW.favorited_at IS NULL
  AND NEW.album_pick_version IS NOT NULL
  AND NEW.album_pick_version IS OLD.album_pick_version
BEGIN
  UPDATE media
  SET album_pick_version = NULL
  WHERE id = NEW.id
    AND favorited_at IS NULL
    AND album_pick_version IS NEW.album_pick_version;
END;

CREATE TRIGGER media_delivery_sequence_insert
AFTER INSERT ON media
WHEN NEW.upload_state = 'stored' AND NEW.delivery_sequence IS NULL
BEGIN
  UPDATE events SET last_delivery_sequence = last_delivery_sequence + 1
  WHERE id = NEW.event_id;
  UPDATE media SET delivery_sequence = (
    SELECT last_delivery_sequence FROM events WHERE id = NEW.event_id
  ) WHERE id = NEW.id;
END;

CREATE TRIGGER media_delivery_sequence_stored
AFTER UPDATE OF upload_state ON media
WHEN NEW.upload_state = 'stored' AND NEW.delivery_sequence IS NULL
BEGIN
  UPDATE events SET last_delivery_sequence = last_delivery_sequence + 1
  WHERE id = NEW.event_id;
  UPDATE media SET delivery_sequence = (
    SELECT last_delivery_sequence FROM events WHERE id = NEW.event_id
  ) WHERE id = NEW.id;
END;

CREATE TRIGGER media_object_promotion_inventory_insert
AFTER INSERT ON media
WHEN NEW.deleted_at IS NULL
  AND NEW.object_bucket_generation = 'legacy'
  AND (
    NEW.upload_state = 'reserved'
    OR NEW.upload_state = 'stored'
  )
BEGIN
  INSERT INTO media_object_promotions (
    media_id, event_id, source_object_key, final_object_key,
    source_writable_until, state, created_at, updated_at
  ) VALUES (
    NEW.id, NEW.event_id, NEW.object_key,
    'events/' || NEW.event_id || '/media/final/' || NEW.id,
    NEW.reservation_expires_at, 'pending',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ) ON CONFLICT (media_id) DO UPDATE SET
    source_writable_until = max(
      media_object_promotions.source_writable_until,
      excluded.source_writable_until
    ),
    updated_at = excluded.updated_at
  WHERE NEW.upload_state = 'reserved'
    AND media_object_promotions.state = 'pending'
    AND media_object_promotions.source_bucket_generation = 'legacy'
    AND media_object_promotions.source_object_key = excluded.source_object_key;
END;

CREATE TRIGGER media_object_promotion_inventory_update
AFTER UPDATE OF upload_state, object_key, object_bucket_generation,
  deleted_at, reservation_expires_at ON media
WHEN NEW.deleted_at IS NULL
  AND NEW.object_bucket_generation = 'legacy'
  AND (
    NEW.upload_state = 'reserved'
    OR NEW.upload_state = 'stored'
  )
BEGIN
  INSERT INTO media_object_promotions (
    media_id, event_id, source_object_key, final_object_key,
    source_writable_until, state, created_at, updated_at
  ) VALUES (
    NEW.id, NEW.event_id, NEW.object_key,
    'events/' || NEW.event_id || '/media/final/' || NEW.id,
    NEW.reservation_expires_at, 'pending',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ) ON CONFLICT (media_id) DO UPDATE SET
    source_writable_until = max(
      media_object_promotions.source_writable_until,
      excluded.source_writable_until
    ),
    updated_at = excluded.updated_at
  WHERE NEW.upload_state = 'reserved'
    AND media_object_promotions.state = 'pending'
    AND media_object_promotions.source_bucket_generation = 'legacy'
    AND media_object_promotions.source_object_key = excluded.source_object_key;
END;

CREATE TRIGGER media_object_promotion_reservation_capability_guard
BEFORE UPDATE OF upload_state, object_key, object_bucket_generation,
  reservation_expires_at ON media
WHEN NEW.deleted_at IS NULL
  AND (
    (
      NEW.upload_state = 'reserved'
      AND NEW.object_bucket_generation = 'legacy'
      AND (
        OLD.upload_state <> 'reserved'
        OR NEW.reservation_expires_at > OLD.reservation_expires_at
      )
    )
  )
  AND NOT EXISTS (
    SELECT 1 FROM media_object_promotions AS p
    WHERE p.media_id = NEW.id
      AND p.event_id = NEW.event_id
      AND p.source_bucket_generation = NEW.object_bucket_generation
      AND p.source_object_key = NEW.object_key
      AND (p.state = 'pending' OR (p.state = 'copying'
        AND OLD.upload_state = 'reserved' AND NEW.upload_state = 'reserved'
        AND NEW.object_key = OLD.object_key AND NEW.object_bucket_generation = OLD.object_bucket_generation
        AND p.source_writable_until >= NEW.reservation_expires_at
        AND EXISTS (SELECT 1 FROM media_upload_transfers t JOIN media_upload_assemblies a ON a.transfer_id = t.id
          AND a.attempt = t.attempt AND a.generation = t.generation
          WHERE t.media_id = NEW.id AND t.event_id = NEW.event_id AND t.state = 'processing'
            AND t.completion_token = p.claim_token AND a.completion_token = p.claim_token
            AND a.state = 'completing' AND a.writer_settled_at IS NULL
            AND p.source_etag = 'assembly:' || a.id || ':' || a.expected_sha256
            AND p.source_sha256 = a.expected_sha256 AND p.source_byte_size = a.expected_byte_size
            AND t.expires_at >= NEW.reservation_expires_at AND t.hard_expires_at >= t.expires_at
            AND t.completion_lease_expires_at = p.lease_expires_at)))
  )
BEGIN
  SELECT RAISE(ABORT, 'media reservation capability is fenced');
END;

CREATE TRIGGER media_object_promotion_verified_delete_guard
BEFORE DELETE ON media_object_promotions
WHEN OLD.state = 'target_verified'
BEGIN
  SELECT RAISE(ABORT, 'verified media target requires suppression handoff');
END;

CREATE TRIGGER media_object_promotion_verified_proof_immutable
BEFORE UPDATE ON media_object_promotions
WHEN OLD.state = 'target_verified'
  AND (
    NEW.state NOT IN ('target_verified', 'cleanup_pending')
    OR NEW.media_id IS NOT OLD.media_id
    OR NEW.event_id IS NOT OLD.event_id
    OR NEW.source_bucket_generation IS NOT OLD.source_bucket_generation
    OR NEW.source_object_key IS NOT OLD.source_object_key
    OR NEW.final_bucket_generation IS NOT OLD.final_bucket_generation
    OR NEW.final_object_key IS NOT OLD.final_object_key
    OR NEW.source_etag IS NOT OLD.source_etag
    OR NEW.source_mime_type IS NOT OLD.source_mime_type
    OR NEW.source_byte_size IS NOT OLD.source_byte_size
    OR NEW.source_sha256 IS NOT OLD.source_sha256
    OR NEW.source_width IS NOT OLD.source_width
    OR NEW.source_height IS NOT OLD.source_height
    OR NEW.final_etag IS NOT OLD.final_etag
    OR NEW.target_verified_at IS NOT OLD.target_verified_at
    OR NEW.source_writable_until IS NOT OLD.source_writable_until
    OR NEW.claim_token IS NOT OLD.claim_token
    OR NEW.created_at IS NOT OLD.created_at
  )
BEGIN
  SELECT RAISE(ABORT, 'verified media target proof is immutable');
END;

CREATE TRIGGER media_object_write_tombstone_guard_insert
BEFORE INSERT ON media
WHEN (NEW.object_bucket_generation = 'canonical' AND NEW.preview_object_key IS NOT NULL)
  OR (
    NEW.deleted_at IS NULL
    AND NEW.upload_state IN ('reserved', 'stored')
    AND EXISTS (
      SELECT 1 FROM media_object_write_tombstones AS t
      WHERE t.suppression_started_at IS NOT NULL
        AND t.object_kind NOT IN ('export', 'cover')
        AND (
          (t.event_id = NEW.event_id AND t.media_id = NEW.id
              AND NOT (t.bucket_generation = 'canonical' AND t.object_kind = 'preview'
                AND EXISTS (SELECT 1 FROM media_image_previews p WHERE p.object_key = t.object_key
                  AND p.event_id = t.event_id AND p.media_id = t.media_id AND p.state = 'suppressed')))
          OR (t.bucket_generation = NEW.object_bucket_generation AND t.object_key = NEW.object_key)
          OR (NEW.preview_object_key IS NOT NULL
            AND t.bucket_generation = 'legacy' AND t.object_key = NEW.preview_object_key)
        )
    )
  )
BEGIN
  SELECT RAISE(ABORT, 'media object write target is permanently suppressed');
END;

CREATE TRIGGER media_object_write_tombstone_guard_update
BEFORE UPDATE OF event_id, object_key, object_bucket_generation,
  preview_object_key, upload_state, deleted_at, trashed_at, restore_until ON media
WHEN (NEW.object_bucket_generation = 'canonical' AND NEW.preview_object_key IS NOT NULL)
  OR (
    NEW.deleted_at IS NULL
    AND NEW.upload_state IN ('reserved', 'stored')
    AND CASE WHEN (
      -- The recovery exception.
      OLD.trashed_at IS NOT NULL
      AND OLD.deleted_at = OLD.trashed_at
      AND OLD.upload_state = 'stored'
      AND NEW.upload_state = 'stored'
      AND NEW.trashed_at IS NULL
      AND NEW.restore_until IS NULL
      AND NEW.event_id = OLD.event_id
      AND NEW.object_key = OLD.object_key
      AND NEW.object_bucket_generation = OLD.object_bucket_generation
      AND NEW.preview_object_key IS OLD.preview_object_key
    )
    THEN
      -- Only the pointers this row still uses may block it. A retired
      -- noncurrent alias — a promoted row's suppressed legacy key — is exactly
      -- what promotion was supposed to leave behind, and must not veto Restore.
      EXISTS (
        SELECT 1 FROM media_object_write_tombstones AS t
        WHERE t.suppression_started_at IS NOT NULL
          AND t.object_kind NOT IN ('export', 'cover')
          AND (
            (t.bucket_generation = NEW.object_bucket_generation AND t.object_key = NEW.object_key)
            OR (NEW.preview_object_key IS NOT NULL
              AND t.bucket_generation = 'legacy' AND t.object_key = NEW.preview_object_key)
          )
      )
    ELSE
      EXISTS (
        SELECT 1 FROM media_object_write_tombstones AS t
        WHERE t.suppression_started_at IS NOT NULL
          AND t.object_kind NOT IN ('export', 'cover')
          AND (
            (t.event_id = NEW.event_id AND t.media_id = NEW.id
              AND NOT (t.bucket_generation = 'canonical' AND t.object_kind = 'preview'
                AND EXISTS (SELECT 1 FROM media_image_previews p WHERE p.object_key = t.object_key
                  AND p.event_id = t.event_id AND p.media_id = t.media_id AND p.state = 'suppressed')))
            OR (t.bucket_generation = NEW.object_bucket_generation AND t.object_key = NEW.object_key)
            OR (NEW.preview_object_key IS NOT NULL
              AND t.bucket_generation = 'legacy' AND t.object_key = NEW.preview_object_key)
          )
      )
    END
  )
BEGIN
  SELECT RAISE(ABORT, 'media object write target is permanently suppressed');
END;

CREATE TRIGGER media_object_write_tombstone_immutable
BEFORE UPDATE ON media_object_write_tombstones
WHEN NEW.object_key <> OLD.object_key
  OR NEW.bucket_generation <> OLD.bucket_generation
  OR NEW.event_id <> OLD.event_id
  OR NEW.media_id <> OLD.media_id
  OR NEW.object_kind <> OLD.object_kind
  OR NEW.created_at <> OLD.created_at
  OR (
    OLD.suppression_started_at IS NOT NULL
    AND NEW.suppression_started_at IS NOT OLD.suppression_started_at
  )
BEGIN
  SELECT RAISE(ABORT, 'media object write tombstone identity is immutable');
END;

CREATE TRIGGER media_object_write_tombstone_inventory_insert
AFTER INSERT ON media
BEGIN
  INSERT INTO media_object_write_tombstones (
    bucket_generation, object_key, event_id, media_id, object_kind,
    next_check_at, created_at, updated_at
  )
  SELECT NEW.object_bucket_generation, NEW.object_key, NEW.event_id, NEW.id,
         CASE NEW.object_bucket_generation WHEN 'canonical' THEN 'final' ELSE 'source' END,
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ON CONFLICT (bucket_generation, object_key) DO UPDATE SET updated_at = media_object_write_tombstones.updated_at
  WHERE media_object_write_tombstones.event_id = excluded.event_id
    AND media_object_write_tombstones.media_id = excluded.media_id
    AND media_object_write_tombstones.object_kind = excluded.object_kind;
  SELECT CASE WHEN NOT EXISTS (
      SELECT 1 FROM media_object_write_tombstones
      WHERE bucket_generation = NEW.object_bucket_generation
        AND object_key = NEW.object_key AND event_id = NEW.event_id
        AND media_id = NEW.id
        AND object_kind = CASE NEW.object_bucket_generation
          WHEN 'canonical' THEN 'final' ELSE 'source' END
    ) THEN RAISE(ABORT, 'media object write tombstone ownership collision') END;

  INSERT INTO media_object_write_tombstones (
    bucket_generation, object_key, event_id, media_id, object_kind,
    next_check_at, created_at, updated_at
  ) VALUES (
    'canonical', 'events/' || NEW.event_id || '/media/final/' || NEW.id,
    NEW.event_id, NEW.id, 'final',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ) ON CONFLICT (bucket_generation, object_key) DO UPDATE SET updated_at = media_object_write_tombstones.updated_at
  WHERE media_object_write_tombstones.event_id = excluded.event_id
    AND media_object_write_tombstones.media_id = excluded.media_id
    AND media_object_write_tombstones.object_kind = excluded.object_kind;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM media_object_write_tombstones
    WHERE bucket_generation = 'canonical'
      AND object_key = ('events/' || NEW.event_id || '/media/final/' || NEW.id)
      AND event_id = NEW.event_id AND media_id = NEW.id AND object_kind = 'final'
  ) THEN RAISE(ABORT, 'media object write tombstone ownership collision') END;

  INSERT INTO media_object_write_tombstones (
    bucket_generation, object_key, event_id, media_id, object_kind,
    next_check_at, created_at, updated_at
  ) VALUES (
    'legacy', 'events/' || NEW.event_id || '/previews/' || NEW.id || '.webp',
    NEW.event_id, NEW.id, 'preview',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ) ON CONFLICT (bucket_generation, object_key) DO UPDATE SET updated_at = media_object_write_tombstones.updated_at
  WHERE media_object_write_tombstones.event_id = excluded.event_id
    AND media_object_write_tombstones.media_id = excluded.media_id
    AND media_object_write_tombstones.object_kind = excluded.object_kind;
  SELECT CASE WHEN NOT EXISTS (
    SELECT 1 FROM media_object_write_tombstones
    WHERE bucket_generation = 'legacy'
      AND object_key = ('events/' || NEW.event_id || '/previews/' || NEW.id || '.webp')
      AND event_id = NEW.event_id AND media_id = NEW.id AND object_kind = 'preview'
  ) THEN RAISE(ABORT, 'media object write tombstone ownership collision') END;

  INSERT INTO media_object_write_tombstones (
    bucket_generation, object_key, event_id, media_id, object_kind,
    next_check_at, created_at, updated_at
  )
  SELECT 'legacy', NEW.preview_object_key, NEW.event_id, NEW.id, 'preview',
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE NEW.preview_object_key IS NOT NULL
  ON CONFLICT (bucket_generation, object_key) DO UPDATE SET updated_at = media_object_write_tombstones.updated_at
  WHERE media_object_write_tombstones.event_id = excluded.event_id
    AND media_object_write_tombstones.media_id = excluded.media_id
    AND media_object_write_tombstones.object_kind = excluded.object_kind;
  SELECT CASE WHEN NEW.preview_object_key IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM media_object_write_tombstones
    WHERE bucket_generation = 'legacy' AND object_key = NEW.preview_object_key
      AND event_id = NEW.event_id
      AND media_id = NEW.id AND object_kind = 'preview'
  ) THEN RAISE(ABORT, 'media object write tombstone ownership collision') END;
END;

CREATE TRIGGER media_object_write_tombstone_inventory_update
AFTER UPDATE OF event_id, object_key, object_bucket_generation, preview_object_key ON media
BEGIN
  INSERT INTO media_object_write_tombstones (
    bucket_generation, object_key, event_id, media_id, object_kind,
    next_check_at, created_at, updated_at
  )
  SELECT NEW.object_bucket_generation, NEW.object_key, NEW.event_id, NEW.id,
         CASE NEW.object_bucket_generation WHEN 'canonical' THEN 'final' ELSE 'source' END,
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ON CONFLICT (bucket_generation, object_key) DO UPDATE SET updated_at = media_object_write_tombstones.updated_at
  WHERE media_object_write_tombstones.event_id = excluded.event_id
    AND media_object_write_tombstones.media_id = excluded.media_id
    AND media_object_write_tombstones.object_kind = excluded.object_kind;
  SELECT CASE WHEN NOT EXISTS (
      SELECT 1 FROM media_object_write_tombstones
      WHERE bucket_generation = NEW.object_bucket_generation
        AND object_key = NEW.object_key AND event_id = NEW.event_id
        AND media_id = NEW.id
        AND object_kind = CASE NEW.object_bucket_generation
          WHEN 'canonical' THEN 'final' ELSE 'source' END
    ) THEN RAISE(ABORT, 'media object write tombstone ownership collision') END;

  INSERT INTO media_object_write_tombstones (
    bucket_generation, object_key, event_id, media_id, object_kind,
    next_check_at, created_at, updated_at
  )
  SELECT 'legacy', NEW.preview_object_key, NEW.event_id, NEW.id, 'preview',
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
         strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE NEW.preview_object_key IS NOT NULL
  ON CONFLICT (bucket_generation, object_key) DO UPDATE SET updated_at = media_object_write_tombstones.updated_at
  WHERE media_object_write_tombstones.event_id = excluded.event_id
    AND media_object_write_tombstones.media_id = excluded.media_id
    AND media_object_write_tombstones.object_kind = excluded.object_kind;
  SELECT CASE WHEN NEW.preview_object_key IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM media_object_write_tombstones
    WHERE bucket_generation = 'legacy' AND object_key = NEW.preview_object_key
      AND event_id = NEW.event_id
      AND media_id = NEW.id AND object_kind = 'preview'
  ) THEN RAISE(ABORT, 'media object write tombstone ownership collision') END;
END;

CREATE TRIGGER media_object_write_tombstone_permanent
BEFORE DELETE ON media_object_write_tombstones
BEGIN
  SELECT RAISE(ABORT, 'media object write tombstones are permanent');
END;

CREATE TRIGGER media_recoverable_owner_tombstone_insert
BEFORE INSERT ON media_object_write_tombstones
WHEN NEW.suppression_started_at IS NOT NULL
  AND NEW.object_kind NOT IN ('export', 'cover')
  AND EXISTS (
    SELECT 1 FROM media AS m
    WHERE m.id = NEW.media_id
      AND m.event_id = NEW.event_id
      AND m.upload_state = 'stored'
      AND m.trashed_at IS NOT NULL
      AND m.deleted_at = m.trashed_at
      AND (
        (NEW.bucket_generation = m.object_bucket_generation AND NEW.object_key = m.object_key)
        OR (m.preview_object_key IS NOT NULL
          AND NEW.bucket_generation = 'legacy' AND NEW.object_key = m.preview_object_key)
      )
  )
BEGIN
  SELECT RAISE(ABORT, 'a recoverable photo owns this object');
END;

CREATE TRIGGER media_recoverable_owner_tombstone_suppress
BEFORE UPDATE OF suppression_started_at ON media_object_write_tombstones
WHEN OLD.suppression_started_at IS NULL
  AND NEW.suppression_started_at IS NOT NULL
  AND NEW.object_kind NOT IN ('export', 'cover')
  AND EXISTS (
    SELECT 1 FROM media AS m
    WHERE m.id = NEW.media_id
      AND m.event_id = NEW.event_id
      AND m.upload_state = 'stored'
      AND m.trashed_at IS NOT NULL
      AND m.deleted_at = m.trashed_at
      AND (
        (NEW.bucket_generation = m.object_bucket_generation AND NEW.object_key = m.object_key)
        OR (m.preview_object_key IS NOT NULL
          AND NEW.bucket_generation = 'legacy' AND NEW.object_key = m.preview_object_key)
      )
  )
BEGIN
  SELECT RAISE(ABORT, 'a recoverable photo owns this object');
END;

CREATE TRIGGER media_stamp_stored_at_compat
AFTER UPDATE OF upload_state ON media
FOR EACH ROW
WHEN OLD.upload_state = 'reserved'
  AND NEW.upload_state = 'stored'
  AND NEW.stored_at IS NULL
BEGIN
  UPDATE media
  SET stored_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = NEW.id
    AND stored_at IS NULL;
END;

CREATE TRIGGER media_stored_legacy_guard_insert
BEFORE INSERT ON media
WHEN NEW.deleted_at IS NULL
  AND NEW.upload_state = 'stored'
  AND NEW.object_bucket_generation = 'legacy'
BEGIN
  SELECT RAISE(ABORT, 'legacy stored media creation is fenced');
END;

CREATE TRIGGER media_stored_legacy_guard_update
BEFORE UPDATE OF event_id, upload_state, deleted_at, object_key,
  object_bucket_generation, mime_type, byte_size, width, height,
  trashed_at, restore_until ON media
WHEN NEW.deleted_at IS NULL
  AND NEW.upload_state = 'stored'
  AND NEW.object_bucket_generation = 'legacy'
  AND NOT (
    OLD.deleted_at IS NULL
    AND OLD.upload_state = 'stored'
    AND OLD.object_bucket_generation = 'legacy'
    AND OLD.event_id = NEW.event_id
    AND OLD.object_key = NEW.object_key
    AND OLD.mime_type = NEW.mime_type
    AND OLD.byte_size = NEW.byte_size
    AND OLD.width = NEW.width
    AND OLD.height = NEW.height
  )
  AND NOT (
    -- A grandfathered still-legacy stored row returning from Recently deleted.
    -- Nothing new is created: the same bytes, at the same key, resume being the
    -- same photograph.
    OLD.trashed_at IS NOT NULL
    AND OLD.deleted_at = OLD.trashed_at
    AND OLD.upload_state = 'stored'
    AND OLD.object_bucket_generation = 'legacy'
    AND NEW.trashed_at IS NULL
    AND NEW.restore_until IS NULL
    AND OLD.event_id = NEW.event_id
    AND OLD.object_key = NEW.object_key
    AND OLD.mime_type = NEW.mime_type
    AND OLD.byte_size IS NEW.byte_size
    AND OLD.width IS NEW.width
    AND OLD.height IS NEW.height
  )
BEGIN
  SELECT RAISE(ABORT, 'legacy stored media creation is fenced');
END;

CREATE TRIGGER media_trash_pair_insert
BEFORE INSERT ON media
WHEN (NEW.trashed_at IS NULL) <> (NEW.restore_until IS NULL)
  OR (
    NEW.trashed_at IS NOT NULL
    AND (
      NEW.upload_state <> 'stored'
      OR NEW.deleted_at IS NOT NEW.trashed_at
      OR NEW.restore_until <= NEW.trashed_at
      OR EXISTS (
        SELECT 1 FROM events AS e
        WHERE e.id = NEW.event_id
          AND (
            NEW.restore_until > e.management_access_expires_at
            OR NEW.restore_until > e.purge_after
          )
      )
    )
  )
  OR (
    NEW.trashed_at IS NULL
    AND NEW.upload_state = 'stored'
    AND NEW.deleted_at IS NOT NULL
  )
BEGIN
  SELECT RAISE(ABORT, 'media recovery markers are invalid');
END;

CREATE TRIGGER media_trash_pair_update
BEFORE UPDATE OF trashed_at, restore_until, deleted_at, upload_state, event_id ON media
WHEN (NEW.trashed_at IS NULL) <> (NEW.restore_until IS NULL)
  OR (
    NEW.trashed_at IS NOT NULL
    AND (
      NEW.upload_state <> 'stored'
      OR NEW.deleted_at IS NOT NEW.trashed_at
      OR NEW.restore_until <= NEW.trashed_at
      OR EXISTS (
        SELECT 1 FROM events AS e
        WHERE e.id = NEW.event_id
          AND (
            NEW.restore_until > e.management_access_expires_at
            OR NEW.restore_until > e.purge_after
          )
      )
    )
  )
  -- An active stored row carries none of the three markers. Grandfathered on
  -- OLD, so a pre-0019 row that somehow already held one is still writable.
  OR (
    NEW.trashed_at IS NULL
    AND NEW.upload_state = 'stored'
    AND NEW.deleted_at IS NOT NULL
    AND NOT (OLD.upload_state = 'stored' AND OLD.trashed_at IS NULL AND OLD.deleted_at IS NOT NULL)
  )
BEGIN
  SELECT RAISE(ABORT, 'media recovery markers are invalid');
END;

-- Source for the new ownership schema; the migration contains an explicit copy.
CREATE TABLE mobile_image_schema (
  singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
  version INTEGER NOT NULL CHECK (version = 26),
  protocol INTEGER NOT NULL CHECK (protocol = 1)
);
INSERT INTO mobile_image_schema VALUES (1, 26, 1);
CREATE TRIGGER mobile_image_schema_no_insert BEFORE INSERT ON mobile_image_schema BEGIN SELECT RAISE(ABORT, 'mobile image schema is immutable'); END;
CREATE TRIGGER mobile_image_schema_no_update BEFORE UPDATE ON mobile_image_schema BEGIN SELECT RAISE(ABORT, 'mobile image schema is immutable'); END;
CREATE TRIGGER mobile_image_schema_no_delete BEFORE DELETE ON mobile_image_schema BEGIN SELECT RAISE(ABORT, 'mobile image schema is immutable'); END;

-- A switch can narrow committed release evidence, never manufacture capability.
CREATE TABLE mobile_image_admission (
  case_id TEXT PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  max_original_bytes INTEGER NOT NULL DEFAULT 536870912 CHECK (max_original_bytes BETWEEN 1 AND 536870912),
  revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_at TEXT NOT NULL DEFAULT '1970-01-01T00:00:00.000Z'
);
INSERT INTO mobile_image_admission (case_id) VALUES
  ('apng'),
  ('avif-sequence'),
  ('avif-still'),
  ('bmp'),
  ('dng-bayer'),
  ('dng-jpeg'),
  ('dng-linear'),
  ('dng-proraw'),
  ('dng-proraw-jxl'),
  ('gif-animated'),
  ('gif-still'),
  ('heic-auxiliary'),
  ('heic-grid'),
  ('heic-primary'),
  ('heic-sequence'),
  ('heif-generic'),
  ('jp2'),
  ('jpeg-baseline'),
  ('jpeg-exif-orientation'),
  ('jpeg-hdr'),
  ('jpeg-motion-photo-still'),
  ('jpeg-progressive'),
  ('jpeg-ultra-hdr-gainmap'),
  ('jxl-animated'),
  ('jxl-still'),
  ('live-photo-camera'),
  ('live-photo-library'),
  ('png'),
  ('tiff'),
  ('webp-animated'),
  ('webp-lossless'),
  ('webp-lossy');
CREATE TRIGGER mobile_image_admission_no_insert BEFORE INSERT ON mobile_image_admission BEGIN SELECT RAISE(ABORT, 'unknown mobile image case'); END;
CREATE TRIGGER mobile_image_admission_no_delete BEFORE DELETE ON mobile_image_admission BEGIN SELECT RAISE(ABORT, 'mobile image case is permanent'); END;
CREATE TRIGGER mobile_image_admission_update BEFORE UPDATE ON mobile_image_admission
WHEN NEW.case_id IS NOT OLD.case_id OR NEW.revision <> OLD.revision + 1 OR NEW.updated_at < OLD.updated_at
BEGIN SELECT RAISE(ABORT, 'mobile image admission revision conflict'); END;

CREATE TABLE media_upload_transfers (
  id TEXT PRIMARY KEY,
  media_id TEXT NOT NULL UNIQUE REFERENCES media(id) ON DELETE RESTRICT,
  event_id TEXT NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
  authority_kind TEXT NOT NULL CHECK (authority_kind IN ('guest', 'manager-link', 'manager-account')),
  actor_session_id TEXT NOT NULL REFERENCES event_sessions(id) ON DELETE RESTRICT,
  event_session_id TEXT REFERENCES event_sessions(id) ON DELETE RESTRICT,
  host_session_id TEXT REFERENCES host_sessions(id) ON DELETE RESTRICT,
  account_id TEXT REFERENCES host_accounts(id) ON DELETE RESTRICT,
  family TEXT NOT NULL CHECK (family IN ('jpeg','png','webp','heic','heif','dng','avif','gif','tiff','bmp','jp2','jxl')),
  mime_type TEXT NOT NULL,
  requires_sequence INTEGER NOT NULL CHECK (requires_sequence IN (0, 1)),
  byte_size INTEGER NOT NULL CHECK (byte_size BETWEEN 1 AND 536870912),
  part_bytes INTEGER NOT NULL CHECK (part_bytes = 8388608),
  part_count INTEGER NOT NULL CHECK (part_count = (byte_size + part_bytes - 1) / part_bytes),
  generation INTEGER NOT NULL DEFAULT 1 CHECK (generation > 0),
  attempt INTEGER NOT NULL DEFAULT 1 CHECK (attempt > 0),
  state TEXT NOT NULL DEFAULT 'receiving' CHECK (state IN ('receiving','processing','retryable','delivered','rejected','aborted','expired')),
  initial_expires_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  hard_expires_at TEXT NOT NULL,
  build_fingerprint TEXT NOT NULL CHECK (length(build_fingerprint) = 64 AND build_fingerprint NOT GLOB '*[^0-9a-f]*'),
  admission_case TEXT NOT NULL REFERENCES mobile_image_admission(case_id) ON DELETE RESTRICT,
  completion_token TEXT,
  completion_lease_expires_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (initial_expires_at <= expires_at AND expires_at <= hard_expires_at AND hard_expires_at > created_at),
  CHECK ((authority_kind = 'manager-account' AND event_session_id IS NULL AND host_session_id IS NOT NULL AND account_id IS NOT NULL)
    OR (authority_kind <> 'manager-account' AND event_session_id = actor_session_id AND host_session_id IS NULL AND account_id IS NULL)),
  CHECK ((completion_token IS NULL) = (completion_lease_expires_at IS NULL))
);
CREATE INDEX media_upload_transfers_cleanup ON media_upload_transfers(state, expires_at, id);
CREATE INDEX media_upload_transfers_event ON media_upload_transfers(event_id, id);
CREATE TRIGGER media_upload_transfer_identity BEFORE UPDATE ON media_upload_transfers
WHEN NEW.id IS NOT OLD.id OR NEW.media_id IS NOT OLD.media_id OR NEW.event_id IS NOT OLD.event_id
 OR NEW.authority_kind IS NOT OLD.authority_kind OR NEW.actor_session_id IS NOT OLD.actor_session_id
 OR NEW.event_session_id IS NOT OLD.event_session_id OR NEW.host_session_id IS NOT OLD.host_session_id OR NEW.account_id IS NOT OLD.account_id
 OR NEW.family IS NOT OLD.family OR NEW.mime_type IS NOT OLD.mime_type OR NEW.requires_sequence IS NOT OLD.requires_sequence
 OR NEW.byte_size IS NOT OLD.byte_size OR NEW.part_bytes IS NOT OLD.part_bytes OR NEW.part_count IS NOT OLD.part_count
 OR NEW.build_fingerprint IS NOT OLD.build_fingerprint OR NEW.admission_case IS NOT OLD.admission_case
 OR NEW.created_at IS NOT OLD.created_at OR NEW.initial_expires_at IS NOT OLD.initial_expires_at OR NEW.hard_expires_at IS NOT OLD.hard_expires_at
 OR NEW.generation < OLD.generation OR NEW.attempt < OLD.attempt OR NEW.expires_at < OLD.expires_at
 OR (OLD.state IN ('delivered','rejected','aborted','expired') AND NEW.state <> OLD.state)
BEGIN SELECT RAISE(ABORT, 'immutable upload transfer'); END;
CREATE TRIGGER media_upload_transfer_owner BEFORE INSERT ON media_upload_transfers
WHEN NOT EXISTS (SELECT 1 FROM media m JOIN events e ON e.id = m.event_id
  WHERE m.id = NEW.media_id AND m.event_id = NEW.event_id AND m.uploader_session_id = NEW.actor_session_id
    AND m.mime_type = NEW.mime_type AND m.declared_byte_size = NEW.byte_size
    AND m.upload_state = 'reserved' AND m.deleted_at IS NULL AND e.deleted_at IS NULL)
BEGIN SELECT RAISE(ABORT, 'upload transfer owner mismatch'); END;

CREATE TABLE media_upload_parts (
  transfer_id TEXT NOT NULL REFERENCES media_upload_transfers(id) ON DELETE RESTRICT,
  part_index INTEGER NOT NULL CHECK (part_index >= 0),
  byte_size INTEGER NOT NULL CHECK (byte_size BETWEEN 1 AND 8388608),
  sha256 TEXT NOT NULL CHECK (length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'),
  part_number INTEGER NOT NULL CHECK (part_number = part_index + 1),
  etag TEXT,
  claim_token TEXT NOT NULL,
  generation INTEGER NOT NULL CHECK (generation > 0),
  attempt INTEGER NOT NULL CHECK (attempt > 0),
  state TEXT NOT NULL CHECK (state IN ('writing','accepted','suppressed')),
  writer_lease_expires_at TEXT NOT NULL,
  writer_settled_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (transfer_id, part_index),
  CHECK (state <> 'accepted' OR (etag IS NOT NULL AND length(etag) > 0 AND writer_settled_at IS NOT NULL))
);
CREATE TRIGGER media_upload_part_identity BEFORE UPDATE ON media_upload_parts
WHEN NEW.transfer_id IS NOT OLD.transfer_id OR NEW.part_index IS NOT OLD.part_index OR NEW.part_number IS NOT OLD.part_number
 OR NEW.byte_size IS NOT OLD.byte_size OR NEW.sha256 IS NOT OLD.sha256 OR NEW.created_at IS NOT OLD.created_at
 OR (OLD.state = 'accepted' AND (NEW.etag IS NOT OLD.etag OR NEW.state = 'writing'))
 OR (OLD.state = 'suppressed' AND NEW.state <> 'suppressed')
BEGIN SELECT RAISE(ABORT, 'immutable upload part'); END;

CREATE TABLE media_upload_assemblies (
  id TEXT PRIMARY KEY,
  transfer_id TEXT NOT NULL REFERENCES media_upload_transfers(id) ON DELETE RESTRICT,
  attempt INTEGER NOT NULL CHECK (attempt > 0),
  generation INTEGER NOT NULL CHECK (generation > 0),
  object_key TEXT NOT NULL UNIQUE,
  create_intent_at TEXT NOT NULL,
  multipart_upload_id TEXT,
  create_settled_at TEXT,
  completion_token TEXT,
  completion_lease_expires_at TEXT,
  writer_settled_at TEXT,
  state TEXT NOT NULL CHECK (state IN ('creating','receiving','completing','completed','suppressed','absent')),
  expected_sha256 TEXT CHECK (expected_sha256 IS NULL OR (length(expected_sha256) = 64 AND expected_sha256 NOT GLOB '*[^0-9a-f]*')),
  expected_byte_size INTEGER NOT NULL CHECK (expected_byte_size BETWEEN 1 AND 536870912),
  completed_etag TEXT,
  suppression_started_at TEXT,
  absence_verified_at TEXT,
  multipart_closed_at TEXT,
  updated_at TEXT NOT NULL,
  UNIQUE (transfer_id, attempt),
  CHECK (state <> 'completed' OR (completed_etag IS NOT NULL AND expected_sha256 IS NOT NULL AND writer_settled_at IS NOT NULL AND multipart_closed_at IS NOT NULL)),
  CHECK (state <> 'absent' OR (suppression_started_at IS NOT NULL AND absence_verified_at IS NOT NULL AND multipart_closed_at IS NOT NULL AND create_settled_at IS NOT NULL AND writer_settled_at IS NOT NULL))
);
CREATE TRIGGER media_upload_assembly_identity BEFORE UPDATE ON media_upload_assemblies
WHEN NEW.id IS NOT OLD.id OR NEW.transfer_id IS NOT OLD.transfer_id OR NEW.attempt IS NOT OLD.attempt
 OR NEW.generation IS NOT OLD.generation OR NEW.object_key IS NOT OLD.object_key OR NEW.create_intent_at IS NOT OLD.create_intent_at
 OR NEW.expected_byte_size IS NOT OLD.expected_byte_size
 OR (OLD.multipart_upload_id IS NOT NULL AND NEW.multipart_upload_id IS NOT OLD.multipart_upload_id)
 OR (OLD.expected_sha256 IS NOT NULL AND NEW.expected_sha256 IS NOT OLD.expected_sha256)
 OR (OLD.completed_etag IS NOT NULL AND NEW.completed_etag IS NOT OLD.completed_etag)
 OR (OLD.suppression_started_at IS NOT NULL AND NEW.suppression_started_at IS NOT OLD.suppression_started_at)
 OR (OLD.state IN ('suppressed','absent') AND NEW.state NOT IN ('suppressed','absent'))
 OR (OLD.state = 'absent' AND NEW.state <> 'absent')
BEGIN SELECT RAISE(ABORT, 'immutable upload assembly'); END;
CREATE TRIGGER media_upload_assembly_delete BEFORE DELETE ON media_upload_assemblies
WHEN OLD.state <> 'absent' BEGIN SELECT RAISE(ABORT, 'upload assembly cleanup unproved'); END;
CREATE TRIGGER media_upload_part_delete BEFORE DELETE ON media_upload_parts
WHEN OLD.writer_settled_at IS NULL OR EXISTS (SELECT 1 FROM media_upload_assemblies a WHERE a.transfer_id = OLD.transfer_id AND a.state <> 'absent')
BEGIN SELECT RAISE(ABORT, 'upload part writer unsettled'); END;
CREATE TRIGGER media_upload_transfer_delete BEFORE DELETE ON media_upload_transfers
WHEN OLD.state NOT IN ('delivered','rejected','aborted','expired')
BEGIN SELECT RAISE(ABORT, 'upload transfer active'); END;
CREATE TRIGGER media_upload_transfer_fence AFTER UPDATE OF generation ON media_upload_transfers
WHEN NEW.generation > OLD.generation BEGIN
  UPDATE media_upload_parts SET state = 'suppressed' WHERE transfer_id = NEW.id;
  UPDATE media_upload_assemblies SET state = CASE WHEN state = 'absent' THEN state ELSE 'suppressed' END,
    suppression_started_at = COALESCE(suppression_started_at,NEW.updated_at) WHERE transfer_id = NEW.id;
  UPDATE media_processing SET state = 'suppressed', generation = generation + 1 WHERE transfer_id = NEW.id;
  UPDATE media_image_previews SET state = 'suppressed', suppression_started_at = COALESCE(suppression_started_at,NEW.updated_at) WHERE media_id = NEW.media_id;
END;

CREATE TABLE media_processing (
  media_id TEXT PRIMARY KEY REFERENCES media(id) ON DELETE RESTRICT,
  transfer_id TEXT REFERENCES media_upload_transfers(id) ON DELETE RESTRICT,
  generation INTEGER NOT NULL CHECK (generation > 0),
  attempt INTEGER NOT NULL CHECK (attempt > 0),
  state TEXT NOT NULL CHECK (state IN ('pending','ready','unavailable','unsupported','suppressed')),
  actual_family TEXT,
  width INTEGER CHECK (width > 0), height INTEGER CHECK (height > 0),
  frame_count INTEGER CHECK (frame_count BETWEEN 1 AND 1024),
  is_sequence INTEGER CHECK (is_sequence IN (0,1)),
  source_sha256 TEXT CHECK (source_sha256 IS NULL OR (length(source_sha256) = 64 AND source_sha256 NOT GLOB '*[^0-9a-f]*')),
  byte_size INTEGER CHECK (byte_size BETWEEN 1 AND 536870912),
  build_fingerprint TEXT CHECK (build_fingerprint IS NULL OR (length(build_fingerprint) = 64 AND build_fingerprint NOT GLOB '*[^0-9a-f]*')),
  preview_profile TEXT,
  failure_code TEXT CHECK (failure_code IN ('unsupported','malformed','resource_limit','busy','unavailable')),
  updated_at TEXT NOT NULL,
  CHECK (state <> 'ready' OR (actual_family IS NOT NULL AND width IS NOT NULL AND height IS NOT NULL AND frame_count IS NOT NULL AND is_sequence IS NOT NULL
    AND source_sha256 IS NOT NULL AND byte_size IS NOT NULL AND build_fingerprint IS NOT NULL AND preview_profile IS NOT NULL AND failure_code IS NULL))
);

CREATE TABLE media_image_previews (
  id TEXT PRIMARY KEY,
  media_id TEXT NOT NULL REFERENCES media(id) ON DELETE RESTRICT,
  event_id TEXT NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
  source_sha256 TEXT NOT NULL CHECK (length(source_sha256) = 64 AND source_sha256 NOT GLOB '*[^0-9a-f]*'),
  profile TEXT NOT NULL,
  generation INTEGER NOT NULL CHECK (generation > 0),
  object_key TEXT NOT NULL UNIQUE,
  mime_type TEXT NOT NULL CHECK (mime_type IN ('image/jpeg','image/webp')),
  state TEXT NOT NULL CHECK (state IN ('pending','ready','suppressed')),
  byte_size INTEGER CHECK (byte_size BETWEEN 1 AND 20971520),
  sha256 TEXT CHECK (sha256 IS NULL OR (length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*')),
  etag TEXT,
  width INTEGER CHECK (width BETWEEN 1 AND 1600), height INTEGER CHECK (height BETWEEN 1 AND 1600),
  frame_count INTEGER CHECK (frame_count BETWEEN 1 AND 1024),
  claim_token TEXT NOT NULL,
  producer_kind TEXT NOT NULL DEFAULT 'upload' CHECK (producer_kind IN ('upload','workflow')),
  run_count INTEGER NOT NULL DEFAULT 0 CHECK (run_count BETWEEN 0 AND 3),
  failure_code TEXT CHECK (failure_code IN ('busy','unavailable','unsupported','malformed','resource_limit')),
  writer_lease_expires_at TEXT NOT NULL,
  writer_settled_at TEXT,
  suppression_started_at TEXT,
  absence_verified_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (media_id, source_sha256, profile, generation),
  CHECK (object_key = 'events/' || event_id || '/media/previews/' || media_id || '/' || source_sha256 || '/' || profile || '/' || generation || CASE mime_type WHEN 'image/webp' THEN '.webp' ELSE '.jpg' END),
  CHECK (state <> 'ready' OR (byte_size IS NOT NULL AND sha256 IS NOT NULL AND etag IS NOT NULL AND width IS NOT NULL AND height IS NOT NULL AND frame_count IS NOT NULL AND writer_settled_at IS NOT NULL)),
  CHECK (state <> 'suppressed' OR suppression_started_at IS NOT NULL)
);
CREATE UNIQUE INDEX media_image_preview_active ON media_image_previews(media_id, source_sha256, profile) WHERE state <> 'suppressed';
CREATE INDEX media_image_preview_event ON media_image_previews(event_id, state, id);
CREATE TRIGGER media_image_preview_identity BEFORE UPDATE ON media_image_previews
WHEN NEW.id IS NOT OLD.id OR NEW.media_id IS NOT OLD.media_id OR NEW.event_id IS NOT OLD.event_id
 OR NEW.source_sha256 IS NOT OLD.source_sha256 OR NEW.profile IS NOT OLD.profile OR NEW.generation IS NOT OLD.generation
 OR NEW.object_key IS NOT OLD.object_key OR NEW.mime_type IS NOT OLD.mime_type OR NEW.producer_kind IS NOT OLD.producer_kind
 OR (NEW.claim_token IS NOT OLD.claim_token AND NOT (OLD.state = 'pending' AND NEW.state = 'pending'
   AND OLD.producer_kind = 'workflow' AND OLD.writer_settled_at IS NOT NULL AND NEW.writer_settled_at IS NULL
   AND NEW.run_count = OLD.run_count + 1))
 OR (OLD.sha256 IS NOT NULL AND (NEW.sha256 IS NOT OLD.sha256 OR NEW.byte_size IS NOT OLD.byte_size
   OR NEW.width IS NOT OLD.width OR NEW.height IS NOT OLD.height OR NEW.frame_count IS NOT OLD.frame_count))
 OR NEW.created_at IS NOT OLD.created_at OR (OLD.state = 'suppressed' AND NEW.state <> 'suppressed')
 OR (OLD.state = 'ready' AND (NEW.byte_size IS NOT OLD.byte_size OR NEW.sha256 IS NOT OLD.sha256 OR NEW.etag IS NOT OLD.etag
   OR NEW.width IS NOT OLD.width OR NEW.height IS NOT OLD.height OR NEW.frame_count IS NOT OLD.frame_count))
BEGIN SELECT RAISE(ABORT, 'immutable image preview'); END;
CREATE TRIGGER media_image_preview_owner BEFORE INSERT ON media_image_previews
WHEN NOT EXISTS (SELECT 1 FROM media m JOIN events e ON e.id = m.event_id WHERE m.id = NEW.media_id AND m.event_id = NEW.event_id
  AND m.upload_state IN ('reserved','stored') AND m.deleted_at IS NULL AND e.deleted_at IS NULL)
BEGIN SELECT RAISE(ABORT, 'image preview owner unavailable'); END;
CREATE TRIGGER media_image_preview_inventory AFTER INSERT ON media_image_previews BEGIN
  INSERT OR IGNORE INTO media_object_write_tombstones (bucket_generation,object_key,event_id,media_id,object_kind,next_check_at,created_at,updated_at)
    VALUES ('canonical',NEW.object_key,NEW.event_id,NEW.media_id,'preview',NEW.created_at,NEW.created_at,NEW.created_at);
  SELECT RAISE(ABORT, 'image preview key suppressed or collision') WHERE NOT EXISTS (SELECT 1 FROM media_object_write_tombstones t
    WHERE t.bucket_generation = 'canonical' AND t.object_key = NEW.object_key AND t.event_id = NEW.event_id AND t.media_id = NEW.media_id
      AND t.object_kind = 'preview' AND t.suppression_started_at IS NULL);
END;
CREATE TRIGGER media_image_preview_delete BEFORE DELETE ON media_image_previews
WHEN OLD.state <> 'suppressed' OR OLD.writer_settled_at IS NULL OR OLD.absence_verified_at IS NULL
BEGIN SELECT RAISE(ABORT, 'image preview cleanup unproved'); END;
CREATE TRIGGER media_image_preview_generation_retained BEFORE DELETE ON media_image_previews
WHEN EXISTS (SELECT 1 FROM media m JOIN events e ON e.id = m.event_id WHERE m.id = OLD.media_id AND e.deleted_at IS NULL
  AND (m.deleted_at IS NULL OR (m.trashed_at IS NOT NULL AND m.deleted_at = m.trashed_at)))
BEGIN SELECT RAISE(ABORT, 'image preview generation retained'); END;
CREATE TRIGGER mobile_preview_tombstone_suppress BEFORE UPDATE OF suppression_started_at ON media_object_write_tombstones
WHEN NEW.suppression_started_at IS NOT NULL AND NEW.bucket_generation = 'canonical' AND NEW.object_kind = 'preview'
 AND EXISTS (SELECT 1 FROM media_image_previews p JOIN media m ON m.id = p.media_id JOIN events e ON e.id = m.event_id
   WHERE p.object_key = NEW.object_key AND p.state <> 'suppressed' AND e.deleted_at IS NULL
     AND (m.deleted_at IS NULL OR (m.trashed_at IS NOT NULL AND m.deleted_at = m.trashed_at)))
BEGIN SELECT RAISE(ABORT, 'image preview owner retained'); END;

-- These triggers also protect old deployed code operating on the upgraded DB.
-- Trash retains a derivative; permanent deletion and event deletion fence it.
CREATE TRIGGER mobile_image_media_fence AFTER UPDATE OF deleted_at, upload_state ON media
WHEN (NEW.deleted_at IS NOT NULL AND NOT (NEW.trashed_at IS NOT NULL AND NEW.deleted_at = NEW.trashed_at)) OR NEW.upload_state IN ('failed','deleted')
BEGIN
  UPDATE media_upload_transfers SET generation = generation + 1,
    state = CASE WHEN state IN ('receiving','processing','retryable') THEN 'aborted' ELSE state END,
    completion_token = NULL, completion_lease_expires_at = NULL, updated_at = COALESCE(NEW.deleted_at, updated_at) WHERE media_id = NEW.id;
  UPDATE media_upload_parts SET state = 'suppressed' WHERE transfer_id IN (SELECT id FROM media_upload_transfers WHERE media_id = NEW.id);
  UPDATE media_upload_assemblies SET state = CASE WHEN state = 'absent' THEN state ELSE 'suppressed' END,
    suppression_started_at = COALESCE(suppression_started_at, NEW.deleted_at, updated_at)
    WHERE transfer_id IN (SELECT id FROM media_upload_transfers WHERE media_id = NEW.id);
  UPDATE media_processing SET state = 'suppressed', generation = generation + 1 WHERE media_id = NEW.id;
  UPDATE media_image_previews SET state = 'suppressed', suppression_started_at = COALESCE(suppression_started_at,NEW.deleted_at,updated_at) WHERE media_id = NEW.id;
END;
CREATE TRIGGER mobile_image_event_fence AFTER UPDATE OF deleted_at ON events WHEN NEW.deleted_at IS NOT NULL BEGIN
  UPDATE media_upload_transfers SET generation = generation + 1,
    state = CASE WHEN state IN ('receiving','processing','retryable') THEN 'aborted' ELSE state END,
    completion_token = NULL, completion_lease_expires_at = NULL, updated_at = NEW.deleted_at WHERE event_id = NEW.id;
  UPDATE media_upload_parts SET state = 'suppressed' WHERE transfer_id IN (SELECT id FROM media_upload_transfers WHERE event_id = NEW.id);
  UPDATE media_upload_assemblies SET state = CASE WHEN state = 'absent' THEN state ELSE 'suppressed' END,
    suppression_started_at = COALESCE(suppression_started_at, NEW.deleted_at)
    WHERE transfer_id IN (SELECT id FROM media_upload_transfers WHERE event_id = NEW.id);
  UPDATE media_processing SET state = 'suppressed', generation = generation + 1 WHERE media_id IN (SELECT id FROM media WHERE event_id = NEW.id);
  UPDATE media_image_previews SET state = 'suppressed', suppression_started_at = COALESCE(suppression_started_at,NEW.deleted_at) WHERE event_id = NEW.id;
END;
CREATE TRIGGER mobile_image_event_purge_guard BEFORE DELETE ON events
WHEN EXISTS (SELECT 1 FROM media_upload_transfers WHERE event_id = OLD.id)
 OR EXISTS (SELECT 1 FROM media_image_previews WHERE event_id = OLD.id)
 OR EXISTS (SELECT 1 FROM media_processing p JOIN media m ON m.id = p.media_id WHERE m.event_id = OLD.id)
BEGIN SELECT RAISE(ABORT, 'mobile image inventory must settle before event purge'); END;


PRAGMA defer_foreign_keys = OFF;
