#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

required_node=22
required_npm=11
node_major="$(node --version | sed -E 's/^v([0-9]+).*/\1/')"
npm_major="$(npm --version | sed -E 's/^([0-9]+).*/\1/')"

if (( node_major < required_node )); then
  printf 'Node.js %s+ is required (found %s).\n' "$required_node" "$(node --version)" >&2
  exit 1
fi

if (( npm_major < required_npm )); then
  printf 'npm %s+ is required (found %s).\n' "$required_npm" "$(npm --version)" >&2
  exit 1
fi

printf 'Installing dependencies from package-lock.json...\n'
npm ci --no-audit --no-fund

if [[ ! -f .dev.vars ]]; then
  printf 'Creating local development secrets in .dev.vars...\n'
  random_secret() {
    node -e "process.stdout.write(require('node:crypto').randomBytes(32).toString('base64url'))"
  }

  cat > .dev.vars <<EOF
# Generated by scripts/setup-codex.sh for local development only.
APP_ORIGIN=http://localhost:5173
TOKEN_HMAC_KEY=$(random_secret)
SESSION_HMAC_KEY=$(random_secret)
GUEST_TOKEN_ENCRYPTION_KEY=$(random_secret)
LOGIN_HMAC_KEY=$(random_secret)
ENTRY_HMAC_KEY=$(random_secret)
ENTRY_ENCRYPTION_KEY=$(random_secret)
RSVP_LOOKUP_HMAC_KEY=$(random_secret)
# Dummy local values. Browser-direct R2 requests need real credentials.
R2_ACCESS_KEY_ID=local-development-only
R2_SECRET_ACCESS_KEY=local-development-only
EOF
else
  printf 'Keeping existing .dev.vars.\n'
fi

printf 'Applying D1 migrations to the local Wrangler database...\n'
npx wrangler d1 migrations apply candidary-core --local

printf '\nCandidary is ready. Run `npm run check` or `npm run dev`.\n'
