import { Search } from 'lucide-react';

import type {
  RsvpHouseholdFilter,
  RsvpHouseholdListItem,
  RsvpSummary,
} from '../../../shared/contracts';

// The eight approved totals, in the order a host reads them: how many people were
// invited, then what they have said, then how many households are still out.
const TOTALS = [
  { key: 'invitedCapacity', label: 'Invited capacity' },
  { key: 'namedInvitees', label: 'Named invitees' },
  { key: 'plusOneCapacity', label: 'Plus-one capacity' },
  { key: 'attending', label: 'Attending' },
  { key: 'declined', label: 'Declined' },
  { key: 'awaitingResponse', label: 'Awaiting response' },
  { key: 'householdsResponded', label: 'Households responded' },
  { key: 'householdsAwaitingResponse', label: 'Households awaiting response' },
] as const satisfies ReadonlyArray<{ key: keyof RsvpSummary; label: string }>;

const STATES: ReadonlyArray<{ value: RsvpHouseholdFilter; label: string }> = [
  { value: 'all', label: 'All households' },
  { value: 'responded', label: 'Responded' },
  { value: 'awaiting', label: 'Awaiting response' },
  { value: 'archived', label: 'Archived households' },
];

interface ManagerRsvpDashboardProps {
  summary: RsvpSummary | null;
  households: RsvpHouseholdListItem[];
  nextCursor: string | null;
  loading: boolean;
  query: string;
  state: RsvpHouseholdFilter;
  selectedId: string | null;
  exportHref: string;
  onQueryChange: (value: string) => void;
  onStateChange: (value: RsvpHouseholdFilter) => void;
  onOpenHousehold: (householdId: string) => void;
  onLoadMore: () => void;
}

export function ManagerRsvpDashboard({
  summary,
  households,
  nextCursor,
  loading,
  query,
  state,
  selectedId,
  exportHref,
  onQueryChange,
  onStateChange,
  onOpenHousehold,
  onLoadMore,
}: ManagerRsvpDashboardProps) {
  return <div className="rsvp-manager__dashboard">
    <div className="rsvp-manager__totals">
      {TOTALS.map(({ key, label }) => <div className="rsvp-total" role="group" aria-label={label} key={key}>
        <strong>{summary ? summary[key] : '—'}</strong>
        <span>{label}</span>
      </div>)}
    </div>

    <div className="rsvp-manager__filters">
      <div className="rsvp-manager__search">
        <label htmlFor="rsvp-manager-query">Search guest list</label>
        <span className="rsvp-manager__search-field">
          <Search aria-hidden="true" />
          <input
            id="rsvp-manager-query"
            type="search"
            value={query}
            autoComplete="off"
            placeholder="Household or guest name"
            onChange={(change) => onQueryChange(change.target.value)}
          />
        </span>
      </div>
      <div className="rsvp-manager__state">
        <label htmlFor="rsvp-manager-state">Response status</label>
        <select
          id="rsvp-manager-state"
          value={state}
          onChange={(change) => onStateChange(change.target.value as RsvpHouseholdFilter)}
        >
          {STATES.map(({ value, label }) => <option key={value} value={value}>{label}</option>)}
        </select>
      </div>
      {/* A plain link, not a fetch: the CSV is generated by the server for the
          current roster and downloaded by the browser like any other file. */}
      <a className="button button--secondary" href={exportHref} download>Download current CSV</a>
    </div>

    {households.length === 0
      ? <p className="rsvp-manager__empty">{loading
        ? 'Loading households…'
        : 'No households match these filters yet.'}</p>
      : <ul className="rsvp-household-list">
        {households.map((household) => <li key={household.id}>
          <button
            type="button"
            className={household.id === selectedId ? 'active' : ''}
            aria-pressed={household.id === selectedId}
            onClick={() => onOpenHousehold(household.id)}
          >
            <span className="rsvp-household-list__label">{household.label}</span>
            <span className="rsvp-household-list__counts">
              {household.attending} attending · {household.declined} not attending
              {' '}· {household.awaitingResponse} awaiting
            </span>
            {household.archivedAt && <span className="rsvp-household-list__flag">Archived</span>}
          </button>
        </li>)}
      </ul>}

    {nextCursor && <div className="rsvp-manager__more">
      <button
        type="button"
        className="button button--secondary"
        disabled={loading}
        onClick={onLoadMore}
      >Load more households</button>
    </div>}
  </div>;
}
